### ISSUE TITLE
Gradle Build Manual

### ISSUE THREAD

**Issue by asimaruk** [pubnative/pubnative-android-library#1]
I'm trying to include pubnative-library using gradle. When I try to build my project it throws error

/home/saharuk/workspace/topface-android/libs/pubnative-android-library/pubnative-library/src/net/pubnative/library/vast/VastAd.java
Error:(70, 39) error: cannot find symbol class Model
Error:(68, 19) error: type argument Creative is not within bounds of type-variable E
where E is a type-variable:
E extends Object declared in class ArrayList

here is my gradle.build for pubnative-library

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
    }
}

apply plugin: 'com.android.library'

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
}

android {
    compileSdkVersion 17
    buildToolsVersion "21.1.1"

    defaultConfig {
        minSdkVersion 10
        targetSdkVersion 16
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }
}

**Comment by asimaruk** [comment]
Here is raw gradle output

    /home/saharuk/workspace/topface-android/libs/pubnative-android-library/pubnative-library/src/net/pubnative/library/vast/VastAd.java:70: error: cannot find symbol
    	public static class Creative extends Model {
    	                                     ^
      symbol:   class Model
      location: class VastAd
    :libs:IllustratedTextView:processReleaseJavaRes UP-TO-DATE
    :libs:IllustratedTextView:packageReleaseJar
    /home/saharuk/workspace/topface-android/libs/pubnative-android-library/pubnative-library/src/net/pubnative/library/vast/VastAd.java:68: error: type argument Creative is not within bounds of type-variable E
	public ArrayList<Creative> creatives;
	                 ^
      where E is a type-variable:
        E extends Object declared in class ArrayList

**Comment by yanchenko** [comment]
I think you need the following dependency:
dependencies {
   compile 'org.droidparts:droidparts:2.5.0'
}

**Comment by asimaruk** [comment]
But it is already in libs folder and I have it dependencies 
compile fileTree(dir: 'libs', include: '*.jar')

I also tried adding compile 'org.droidparts:droidparts:2.5.0' both in my main and pubnative-library projects and it didn't help.

**Comment by yanchenko** [comment]
Agreed. Could you please also try changing     minSdkVersion 10 to     minSdkVersion 14 and see if it helps?
If it doesn't, could you please also paste the relevant sections of you main app's build.gradle so I could reproduce the issue?
Thanks!

**Comment by yanchenko** [comment]
Added a workaround in 7ffad6ac8d9fa3cfc5960e27177fb9a9822aa87c
