### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by xgear-public** [pubnative/pubnative-android-library#35]
I am interested in possible icon sizes.

AdRequest request = new AdRequest(context);
request.setParameter(Request.ICON_SIZE, "200x200");

What is server logic of icon size selection? When I provide icon size calculated from dp (48dp) i receive icons which are smaller and it looks bad. Which icon sizes service can provide and how it decide which one from this sizes to chose?

**Comment by cerberillo** [comment]
Hello:

The possible Icon sizes are:

"80x80"
"100x100"
"150x150"
"200x200"
"256x256"
"300x300"
"400x400"

You have to manually manage the screen size in order to request the one that better fits the device screen size
