### ISSUE TITLE
Manifest merge conflict

### ISSUE THREAD

**Issue by voidshad** [pubnative/pubnative-android-library#59]
Hello
I have ran into a small problem with you library.
If I add it as a dependency via gradle, build always fails because of conflict on manifest merge state.
The cause of it is two application attributes (allowBackup and label), defined in your manifest. So they are conflicting with attributes from my application manifest. That`s why I have to use such things as tools:replace or tools:node="replace" which is inconvenient (manifest merger still is really buggy, for example,  tools:replace doesn`t work with tools:ignore marker declared into the same node).

Could you remove those attributes or there is a reason why you do need them?

**Comment by cerberillo** [comment]
@voidshad thanks for the info on the conflicts, I'm going to clean the library manifest and release a new version today

**Comment by cerberillo** [comment]
Solved in PR #62 you should be able to get it from gradle as version 1.4.9, thanks

**Comment by voidshad** [comment]
Great. Thanks a lot.
