### ISSUE TITLE
Location permission implicit declaration

### ISSUE THREAD

**Issue by voidshad** [pubnative/pubnative-android-library#60]
Hello
I have noticed that you library manifest contains 
` <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>` 
Thus, if installing your library via gradle dependencies, it will implicitly add this permission to an application manifest. And this can be tricky to spot.
I believe, such thing must be mentioned in docs, at least.  And maybe it`s even better to remove it from manifest and make it optional.

**Comment by cerberillo** [comment]
@voidshad yeah I'm going to clean all that and will release a new version today, thanks for the info

**Comment by cerberillo** [comment]
Solved in PR #62

**Comment by voidshad** [comment]
Thanks for fast respond.
